# Site settings
name: Farel Reyhananda Nugraha
title: Farel Reyhananda Nugraha | Fullstack Software Engineer
description: Fullstack software engineer eagered on exploring vast world of tech and adapting to new challenges
url: https://farel14.github.io/
baseurl: ''
email: farel.reyhananda@gmail.com
cover: https://farel14.github.io/img/og.png
logo: https://farel14.github.io/img/emojis/laptop.png
resume: https://farel14.github.io/resume.pdf
social:
  - title: email
    url: mailto:farel.reyhananda@gmail.com
  - title: twitter
    url: https://twitter.com/farel14
  - title: instagram
    url: https://instagram.com/farel14
  - title: codepen
    url: http://codepen.io/farel14
  - title: github
    url: https://github.com/farel14
  - title: linkedin
    url: https://www.linkedin.com/in/farel14

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
